# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\Downloads\Freelancing_Projects\pyqt ui\openCVDashboardwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 878)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #2b2b2b;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #3c3f41;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #1e1e1e;\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 120, 300, 650))
        self.frame.setMinimumSize(QtCore.QSize(250, 650))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 60, 258, 349))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.projectDropdown = QtWidgets.QComboBox(self.widget)
        self.projectDropdown.setObjectName("projectDropdown")
        self.projectDropdown.addItem("")
        self.projectDropdown.addItem("")
        self.projectDropdown.addItem("")
        self.projectDropdown.addItem("")
        self.projectDropdown.addItem("")
        self.verticalLayout.addWidget(self.projectDropdown)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.widget)
        self.runButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}")
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(self.widget)
        self.stopButton.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f;\n"
"}\n"
"")
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.statusLabel = QtWidgets.QLabel(self.widget)
        self.statusLabel.setStyleSheet("QLabel {\n"
"    color: #00E676;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    font-family: Consolas;\n"
"}")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.captureButton = QtWidgets.QPushButton(self.widget)
        self.captureButton.setStyleSheet("QPushButton {\n"
"    background-color: #FF6D00;\n"
"    color: white;\n"
"    border: 2px solid #FF9100;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF9100;\n"
"}")
        self.captureButton.setObjectName("captureButton")
        self.verticalLayout.addWidget(self.captureButton)
        self.teachButton = QtWidgets.QPushButton(self.widget)
        self.teachButton.setStyleSheet("QPushButton {\n"
"    background-color: #2962FF;\n"
"    color: white;\n"
"    border: 2px solid #448AFF;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #448AFF;\n"
"}")
        self.teachButton.setObjectName("teachButton")
        self.verticalLayout.addWidget(self.teachButton)
        self.outputConsoleLabel = QtWidgets.QLabel(self.widget)
        self.outputConsoleLabel.setStyleSheet("QLabel {\n"
"    color: #39FF14;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    font-family: Consolas;\n"
"}")
        self.outputConsoleLabel.setObjectName("outputConsoleLabel")
        self.verticalLayout.addWidget(self.outputConsoleLabel)
        self.outputWindow = QtWidgets.QTextEdit(self.widget)
        self.outputWindow.setStyleSheet("QTextEdit {\n"
"    background-color: black;\n"
"    color: #39FF14;\n"
"    border: 2px solid #39FF14;\n"
"    font-family: Consolas;\n"
"    font-size: 11pt;\n"
"}")
        self.outputWindow.setPlaceholderText("")
        self.outputWindow.setObjectName("outputWindow")
        self.verticalLayout.addWidget(self.outputWindow)
        self.cameraFrame = QtWidgets.QFrame(self.centralwidget)
        self.cameraFrame.setGeometry(QtCore.QRect(350, 120, 741, 651))
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.cameraFeedTitle = QtWidgets.QLabel(self.cameraFrame)
        self.cameraFeedTitle.setGeometry(QtCore.QRect(10, 10, 711, 21))
        self.cameraFeedTitle.setStyleSheet("QLabel {\n"
"    color: #39FF14;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    font-family: Consolas;\n"
"}")
        self.cameraFeedTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraFeedTitle.setObjectName("cameraFeedTitle")
        self.cameraDisplayLabel = QtWidgets.QLabel(self.cameraFrame)
        self.cameraDisplayLabel.setGeometry(QtCore.QRect(30, 60, 700, 461))
        self.cameraDisplayLabel.setMinimumSize(QtCore.QSize(700, 400))
        self.cameraDisplayLabel.setStyleSheet("QLabel {\n"
"    background-color: black;\n"
"    color: #39FF14;\n"
"    border: 2px solid #39FF14;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.cameraDisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraDisplayLabel.setObjectName("cameraDisplayLabel")
        self.layoutWidget = QtWidgets.QWidget(self.cameraFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 570, 165, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startCameraButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startCameraButton.setStyleSheet("QPushButton {\n"
"    background-color: #00C853;\n"
"    color: white;\n"
"    border: 2px solid #00E676;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00E676;\n"
"}")
        self.startCameraButton.setObjectName("startCameraButton")
        self.horizontalLayout_2.addWidget(self.startCameraButton)
        self.stopCameraButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopCameraButton.setStyleSheet("QPushButton {\n"
"    background-color: #D50000;\n"
"    color: white;\n"
"    border: 2px solid #FF1744;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF1744;\n"
"}")
        self.stopCameraButton.setObjectName("stopCameraButton")
        self.horizontalLayout_2.addWidget(self.stopCameraButton)
        self.dashboardLabel = QtWidgets.QLabel(self.centralwidget)
        self.dashboardLabel.setGeometry(QtCore.QRect(30, 40, 301, 71))
        self.dashboardLabel.setStyleSheet("QLabel {\n"
"    color: #39FF14;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"    font-family: Consolas;\n"
"}")
        self.dashboardLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dashboardLabel.setObjectName("dashboardLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.projectDropdown.setItemText(0, _translate("MainWindow", "Bottle Label Detector"))
        self.projectDropdown.setItemText(1, _translate("MainWindow", "Object Counter"))
        self.projectDropdown.setItemText(2, _translate("MainWindow", "QR Template Matcher"))
        self.projectDropdown.setItemText(3, _translate("MainWindow", "Global Template Matcher"))
        self.projectDropdown.setItemText(4, _translate("MainWindow", "Text Detector"))
        self.runButton.setText(_translate("MainWindow", "Run Project"))
        self.stopButton.setText(_translate("MainWindow", "Stop Project"))
        self.statusLabel.setText(_translate("MainWindow", "Status : Ready"))
        self.captureButton.setText(_translate("MainWindow", "Capture Text"))
        self.teachButton.setText(_translate("MainWindow", "Teach Pattern"))
        self.outputConsoleLabel.setText(_translate("MainWindow", "Output Console"))
        self.cameraFeedTitle.setText(_translate("MainWindow", "Camera Feed"))
        self.cameraDisplayLabel.setText(_translate("MainWindow", "Camera Not Started"))
        self.startCameraButton.setText(_translate("MainWindow", "Start Camera"))
        self.stopCameraButton.setText(_translate("MainWindow", "Stop Camera"))
        self.dashboardLabel.setText(_translate("MainWindow", "OpenCV Vision Dashboard"))
